#import "../../template/shared.typ": *
== Backend

The backend service is `GraphleManager`, a JVM Spring Boot application written in Kotlin.

=== Module and Package Layout

`GraphleManager` is a Gradle multi-project build.
The root project contains the Spring Boot entry point `GraphleManagerApplication.kt`, startup configuration, the background sweeper, and resources.
Backend code is split into subprojects so cross-domain dependencies are visible in `build.gradle.kts`. `GraphleManager` consists of:

- `common`: shared utilities.
- `model`: serializable #voc("api") and Neo4j data classes shared by the domain modules.
- `tag`: #voc("tag") persistance, tag service operations, and the tag #voc("graphql") controller.
- `connection`: #voc("relationship") persistance, connection service operations and the connection #voc("graphql") controller.
- `autocomplete`: Valkey-backed filename #voc("trie") storage, caching, and the autocomplete service contract.
- `file`: #voc("filesystem") interactions, file-node persistence, file mutations and queries, and downloads.
- `application`: cross-domain orchestration.
- `dsl`: #voc("dsl") parsing and execution, the `/dsl` #voc("rest") endpoint, and the autocomplete #voc("websocket").

=== Domain Layer

`File`, `Tag`, and #voc("connection", text: "Connection") are declared as Spring Data Neo4j entities with UUID identifiers generated by the driver.
The `File` node stores the file's absolute path and is linked to its #voc("tag", text: "tags") and #voc("connection", text: "connections").
The `Tag` node has an indexed name and an optional value so the same name can take different values on different files.
A #voc("connection", text: "Connection") is a named, directional edge between two `File` nodes with an optional value and a bidirectional flag.
Hierarchical parent and descendant #voc("relationship", text: "relationships") are not persisted and are instead derived from the live #voc("filesystem") at query time.

Index creation is handled once on startup by `init/Neo4JConfig`, which ensures the mentioned indexes exist.

=== Repository Layer

Each entity has a `Neo4jRepository` declaring the #voc("cypher") queries the rest of the code needs:

- `FileRepository`: `addFileNode`, `removeFileByLocation`, `moveFile`, `getFileLocationsByConnections`.
- `TagRepository`: `tagsByFileLocation`, `addTagToFile`, `removeTag`, `filesByTag`, `removeOrphanTags`.
- `ConnectionRepository`: `neighborsByFileLocation`, `addConnection`, `removeConnection`.

=== Service Layer

Services sit between the controllers and the repositories and carry all non-trivial logic.
`FileService` performs #voc("filesystem") I/O through `java.nio.file.Files`, reconciles database state with disk state after `addFile`/`removeFile`/`moveFile`, and schedules asynchronous autocomplete #voc("trie") updates via `insertFilesToCompleter`.
It exposes functions `fileType`, `descendantsOfFile`, and `parentOfFile` that let the controllers compute hierarchical #voc("neighbor", text: "neighbors") without going through the database (F1, F9).
`TagService` and `ConnectionService` are thin wrappers that delegate to their repositories.
Background work is dispatched on a different thread so the caller does not need to wait and its failure will not affect the rest of the system.

=== Controller Layer

#voc("graphql") surface is split across three `@Controller` classes, one per entity: `FileController`, `TagController`, and `ConnectionController`. Their methods are tagged with the standard query and mutation annotations, and the nested `File.tags` and `File.connections` fields are fetched lazily, only when the client actually requests them.
The `fileByLocation` query is implemented outside those domain controllers in `application/FileDetailsController`, which delegates to `FileDetailsService`.
This service assembles a single `File` response from the live hierarchical #voc("neighbor", text: "neighbors"), the persisted custom #voc("connection", text: "connections"), and the file's #voc("tag", text: "tags").
The separation is enforced by Gradle module dependencies, meaning only application module can access other domain modules. Exceptions thrown inside any of these controllers are caught by `@GraphQlExceptionHandler` methods that translate `IOException` and `FileAlreadyExistsException` into readable #voc("graphql") errors used by the UI.

Three more endpoints sit outside #voc("graphql").
`DSLController` is a `@RestController` mapped at `/dsl` that hands the request body to the #voc("dsl") interpreter and returns the resulting response.
`FileDownloadController` serves raw file contents over `GET /download?location=…` with a detected MIME type. The GUI uses it whenever the backend is running on a different host.
A #voc("websocket") endpoint at `/ws` carries autocomplete traffic.

=== Configuration

The backend reads its settings from `application.properties`, which exposes:

- `server.port`: the #voc("http") port on which the service listens (default 5824). The GUI's `server.port` must match this value for the transports to reach the backend.
- `spring.graphql.graphiql.enabled`: toggles the built-in GraphiQL playground on the same HTTP port.
- The Neo4j connection: bolt URL and credentials consumed by Spring Data Neo4j.
- The Valkey #voc("connection"): host and port that the autocomplete layer dials for #voc("trie") storage.
- `neo4j.sweeper.interval`: how often the background sweeper reconciles the graph with the live #voc("filesystem") (default one minute).
- `cache.ttl`: the expiration applied to Valkey keys held by the autocomplete #voc("trie") (default thirty days).
