#import "../../template/shared.typ": *
== Backend

The backend service is `GraphleManager`, a JVM Spring boot application written in Kotlin.

=== Package Layout

All source lives under `com.graphle.graphlemanager` and is split by domain concern rather than by layer.
The root is the Spring entry point `GraphleManagerApplication.kt`. The subpackages are:

- `init/`: Startup configuration.
- `file/`: file entity and the #link(label("voc_graphql"))[GraphQL]/#link(label("voc_rest"))[REST] endpoints that expose it.
- `tag/`: #link(label("voc_tag"))[tag] entity and the #link(label("voc_graphql"))[GraphQL] endpoints that expose it.
- `connection/`: #link(label("voc_relationship"))[relationship] entity and the #link(label("voc_graphql"))[GraphQL] endpoints that expose it.
- `dsl/`: the #link(label("voc_dsl"))[DSL] interpreter, autocomplete, and the Valkey-backed #link(label("voc_trie"))[trie].
- `sweeper/`: the background cleanup job `Neo4JSweeper`.
- `commons/`: shared utilities.

=== Domain Layer

`File`, `Tag`, and `#link(label("voc_connection"))[Connection]` are declared as Spring Data Neo4j entities with UUID identifiers generated by the driver.
The `File` node stores the file's absolute path and is linked to its #link(label("voc_tag"))[tags] and #link(label("voc_connection"))[connections].
The `Tag` node has an indexed name and an optional value so the same name can take different values on different files.
A `#link(label("voc_connection"))[Connection]` is a named, directional edge between two `File` nodes with an optional value and a bidirectional flag.
Hierarchical parent and descendant #link(label("voc_relationship"))[relationships] are not persisted and are instead derived from the live #link(label("voc_filesystem"))[filesystem] at query time.

Index creation is handled once on startup by `init/Neo4JConfig`, which ensures the mentioned indexes exist.

=== Repository Layer

Each entity has a `Neo4jRepository` declaring the #link(label("voc_cypher"))[Cypher] queries the rest of the code needs:

- `FileRepository`: `addFileNode`, `removeFileByLocation`, `moveFile`, `getFileLocationsByConnections`.
- `TagRepository`: `tagsByFileLocation`, `addTagToFile`, `removeTag`, `filesByTag`, `removeOrphanTags`.
- `ConnectionRepository`: `neighborsByFileLocation`, `addConnection`, `removeConnection`.

=== Service Layer

Services sit between the controllers and the repositories and carry all non-trivial logic.
`FileService` performs #link(label("voc_filesystem"))[filesystem] I/O through `java.nio.file.Files`, reconciles database state with disk state after `addFile`/`removeFile`/`moveFile`, and schedules the autocomplete #link(label("voc_trie"))[trie] updates off the request thread via `insertFilesToCompleter`.
It exposes functions `fileType`, `descendantsOfFile`, and `parentOfFile` that let the controllers compute hierarchical #link(label("voc_neighbor"))[neighbours] without going through the database (F1, F9).
`TagService` and `ConnectionService` are thin wrappers that delegate to their repositories.
Background work is dispatched on a different thread so it does not need to wait and its failure will not affect the rest of the system.

=== Controller Layer

#link(label("voc_graphql"))[GraphQL] surface is split across three `@Controller` classes, one per entity: `FileController`, `TagController`, and `ConnectionController`. Their methods are tagged with the standard query and mutation annotations, and the nested `File.tags` and `File.connections` fields are fetched lazily, only when the client actually requests them.
`FileController.fileByLocation` is the only entry point that crosses domain boundaries: it assembles a single `File` response from the live hierarchical #link(label("voc_neighbor"))[neighbours], the persisted custom #link(label("voc_connection"))[connections], and the file's #link(label("voc_tag"))[tags], optionally hiding entries marked as hidden by the operating system.
Exceptions thrown inside any of these controllers are caught by `@GraphQlExceptionHandler` methods that translate `IOException` and `FileAlreadyExistsException` into readable #link(label("voc_graphql"))[GraphQL] errors.

Three more endpoints sit outside #link(label("voc_graphql"))[GraphQL].
`DSLController` is a `@RestController` mapped at `/dsl` that hands the request body to the #link(label("voc_dsl"))[DSL] interpreter and returns the resulting response.
`FileDownloadController` serves raw file contents over `GET /download?location=…` with a detected MIME type, the GUI uses it whenever the backend is running on a different host.
A #link(label("voc_websocket"))[WebSocket] endpoint at `/ws` carries autocomplete traffic.

=== Configuration

The backend reads its settings from `application.properties`, which exposes:

- `server.port`: the #link(label("voc_http"))[HTTP] port on which the service listens (default 5824). The GUI's `server.port` must match this value for the transports to reach the backend.
- `spring.graphql.graphiql.enabled`: toggles the built-in GraphiQL playground on the same HTTP port.
- The Neo4j connection: bolt URL and credentials consumed by Spring Data Neo4j.
- The Valkey #link(label("voc_connection"))[connection]: host and port that the autocomplete layer dials for #link(label("voc_trie"))[trie] storage.
- `neo4j.sweeper.interval`: how often the background sweeper reconciles the graph with the live #link(label("voc_filesystem"))[filesystem] (default one minute).
- `cache.ttl`: the expiration applied to Valkey keys held by the autocomplete #link(label("voc_trie"))[trie] (default thirty days).
