@startuml
start
:The user opens the file browser;
:The file browser opens the user defined home location;
while (Continue searching for a file) is ( Yes )
:Application shows the graph of possible neighbors from the current location and tags for the file;
if (How does the user want to interact with the system?) then ( GUI )
    :The user clicks on the neighbor they want to visit;
else ( DSL )
    :The user enters a command to search for an item;
endif
endwhile ( No )
:The system displays the selected file or folder;
stop
@enduml
